color verde numeros
CEU-GITAV-INSW/practica-1-2-grupo-1 pull request #53
Opened 2023-12-21 13:23 UTC by GonzaloFrancoGarcia

Los numeros que ingrese el usuario apareceran de color verde.

2023-12-27 12:11 UTC, LUCIA0BGM requested changes
Funciona perfect, pero el color verde no se ve muy bien cuando el fondo es verde ni cuando es rojo. Estaría bien o elegir un color que se vea bien con todos los fondos o que dependiendo del fondo cambiara también el color a uno que contraste.

2023-12-27 17:24 UTC, LUCIA0BGM submitted a review, later dismissed

2023-12-27 17:39 UTC, LUCIA0BGM commented
@GonzaloFrancoGarcia  Puedes comparar con el main a ver qué le falta?

2023-12-27 19:40 UTC, GonzaloFrancoGarcia commented
@LUCIA0BGM Me parece que esta todo

2023-12-28 14:01 UTC, LUCIA0BGM approved these changes
Perdón que estaba mirando un commit anterior. Está perfect

2023-12-28 14:12 UTC, merged